### ISSUE TITLE
Copygen v0.5

### ISSUE THREAD

**Issue by switchupcb** [switchupcb/copygen#34]
Version 0.5 will require the following changes.

- [ ] implement https://github.com/switchupcb/copygen/issues/33
- [ ] Options, Matcher, Generator: cast option for [direct type conversions](https://go.dev/ref/spec#Conversions) (as opposed to a convert function)
  - use `go/types AssignableTo()` function to add casting field (in a similar manner to `map`).

The following changes would be ideal, but cannot be confirmed.

- [ ] https://github.com/switchupcb/copygen/issues/30

**Status**
Not Started.

**ETA**
This target will be started when one of the following situations occur.

- Copygen is sponsored with work time.
- One of these features is needed in a library of significance.
- 2023 Downtime (and https://github.com/golang/go/issues/20744 is fixed).

**Comment by switchupcb** [comment]
`/cast`: https://go.dev/ref/spec#Conversions
`/assert`: https://go.dev/ref/spec#Type_assertions

**Comment by switchupcb** [comment]
### Additional Configuration

Additional configuration may be added to allow the user to specify feature flags.
```yml
matcher:
  cast:
    enabled: true # Determines whether automatic casting is applied to matched fields (default: disabled).
    flags:
      assignObjectInterface: true # Enables assignment of object to interfaces (default: true).
      asertInterfaceObject: true # Enables assertion of interface to object (default: true).
      convert: true # Enables type conversion (default: true).
```
