### ISSUE TITLE
Error: the "type Copygen interface" could not be found in the setup file

### ISSUE THREAD

**Issue by pobearm** [switchupcb/copygen#35]
Please provide the following information.

### YML

```yml
# Define where the code will be generated.
generated:
  setup: ./setup.go
  output: ./copygen.go

  # Define the optional custom templates used to generate the file (.go, .tmpl supported).
  # template: ./generate.go
# Define custom options (which are passed to generator options) for customization.
# custom:
#   option: The possibilities are endless.
```

### Go

```go
package copygen

import (
	"demo/admin/adapters/reposit/dal"
	"demo/admin/domain"
)

type Copygen interface {
	Basic(user *domain.AgrUser) *dal.SysUser
}
```

### Error

```
the "type Copygen interface" could not be found in the setup file
```

### Generation

```go

```

## Environment

**Operating System**: windows 10
**Copygen Version**: 0.4.0
**Golang Version** : 1.19.4
